pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    environment {
        DB_URL = 'jdbc:postgresql://localhost:5433/employeedb'
        DB_USERNAME = 'postgres'
        DB_PASSWORD = 'Sandy@3722'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir('backend') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('backend') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Version') {
            steps {
                bat 'docker --version'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'backend/target/*.jar', fingerprint: true
        }

        success {
            echo 'Build Successful!'
        }

        failure {
            echo 'Build Failed!'
        }
    }

    
}